services:
  - type: web
    name: file-converter
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        value: yeliulzewdu@gmail.com
      - key: EMAIL_PASS
        value: emqj wvdw mqay odsx
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_SECURE
        value: true
